export const CHANGE_FORM = 'CHANGE_FORM';
export const CHANGE_HOURS_FORM = 'CHANGE_HOURS_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SENDING_FORM = 'SENDING_FORM';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const UNAUTH_USER = 'UNAUTH_USER';